version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  user-db:
    image: postgres:13
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  auction-db:
    image: postgres:13
    container_name: auction-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auctiondb
    ports:
      - "5433:5432"
    volumes:
      - auction-db-data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgres://user:password@user-db:5432/userdb?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      GO111MODULE: on
    depends_on:
      - user-db
      - rabbitmq

  auction-service:
    build: ./auction-service
    container_name: auction-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      DATABASE_URL: postgres://user:password@auction-db:5432/auctiondb?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      GO111MODULE: on
    depends_on:
      - auction-db
      - rabbitmq

volumes:
  user-db-data:
  auction-db-data:
